### ISSUE TITLE
Does not return only running time entry

### ISSUE THREAD

**Issue by godbout** [valsplat/harvest-php-client#2]
Hello! Thanks for the package. I'm trying it but I'm having a few issues. This one is related to getting only the running time entry. I'm passing the params but it doesn't seem to work

```php
$timer = $this->client->timeEntry()->list(['is_running' => true]);
```

I do receive all the time entries, not filtered by whether they are running or not. Anything I'm missing?

**Comment by bjornpost** [comment]
Without checking, I guess `(bool)true` is converted by the url lib to `?is_running=1` (iso `?is_running=true`, which Harvest is expecting). Have you tried using `list(['is_running' => 'true'])`?

**Comment by godbout** [comment]
Sorry, I ended up using another library 🙈️
