### ISSUE TITLE
Stopping a running time entry?

### ISSUE THREAD

**Issue by godbout** [valsplat/harvest-php-client#3]
Can't find the way to stop a running entry. I've successfully created one, but it doesn't seem there's a way to reach the `/stop` endpoint with the package? Thanks!

**Comment by bjornpost** [comment]
Hi @godbout!

Thanks for checking out the lib! We're not using this functionality, so we haven't built it yet. But it shouldn't be too hard to add. Basically, it involves adding a `Actions\Stoppable` class which implements a `stop($id)` method (see the other Actions for inspiration). Then, you `use` the `Stoppable` action to the `TimeEntry` entity ([here](https://github.com/valsplat/harvest-php-client/blob/master/src/Valsplat/Harvest/Entities/TimeEntry.php#L13)).

Cheers,
Bjorn

**Comment by godbout** [comment]
Thanks @bjornpost!
